version: '2.2'

services:

  geoserver:
    build: .
    image: rpassmore/geoserver-docker:make-it-day
    container_name: rpassmore-geoserver-docker
    
    ports:
      - "8080:8080"
    volumes:
      #- /srv/docker/geoserver/geoserver:/geoserver_data/data
      #- /var/run/docker.sock:/var/run/docker.sock
      - /home/rob/Documents:/host/files
    
