version: '2.2'

services:

  geoserver:
    build: .
    image: rpassmore/geoserver-docker:make-it-day
    container_name: rpassmore-geoserver-docker

    links:
      - postgis
    ports:
      - "8080:8080"
    volumes:
      # Mount a specific folder on the host as the geoserver data folder
      #- /home/rob/Documents/docker/geoserver/geoserver:/geoserver_data/data
      
      # Add a volume from the host to allow easy transfer of files
      - /home/rob/Documents:/host/files
      
      # Create a volume on the host machine to store the geoserver config,
      # so that it is persisted between container restarts.
      # volume location can be found by using :
      # docker inspect -f "{{json .Mounts}}" rpassmore-geoserver-docker
      - /geoserver_data/data
 
  postgis:
    image: kartoza/postgis
    ports:
      - "25432:5432"
    volumes:
      # -/srv/docker/geoserver/postgis:/var/lib/postgresql
      - /var/lib/postgresql
    #volumes_from:
      #- pgstore
